In [1]:
from pandas import read_csv
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
import numpy

Using TensorFlow backend.


In [2]:
_uri = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [3]:
_dataframe = read_csv(_uri)

In [4]:
_array = _dataframe.values

In [5]:
print(_array[:5,:])

[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']]


In [6]:
_X = _array[:,0:4]

In [7]:
print(_X[:5,:])

[[4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]


In [8]:
_Y = _array[:,4:]

In [9]:
print(_Y[:5])

[['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']]


In [10]:
_Y = numpy.ravel(_Y)

In [11]:
print(_Y[:5])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [12]:
# encode class values as integers
_Y_encoded = LabelEncoder().fit_transform(_Y)

In [13]:
print(_Y_encoded[:5])

[0 0 0 0 0]


In [14]:
# convert integers to dummy variables (one hot encoded)
_Y_1hot = np_utils.to_categorical(_Y_encoded)

In [15]:
print(_Y_1hot[:5])

[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]
