In [11]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline

import run_notebook
import time

In [4]:
run_notebook.execute_notebook('./data/dataset-iris.ipynb')

[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']]
[[4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
[['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']
[0 0 0 0 0]
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]


In [5]:
_seed = 7
numpy.random.seed(_seed)

In [7]:
# The network topology of neural network

# 4 inputs ==> [4 hidden inputs] ==> 3 outputs (because of 1-hot-encoding)

In [8]:
def baseline_model():
    _model = Sequential()
    _model.add(Dense(4, input_dim=4, kernel_initializer='normal', activation='relu'))
    _model.add(Dense(3, kernel_initializer='normal', activation='sigmoid'))
    _model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return _model

In [9]:
_estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)

In [10]:
_kfold = KFold(n_splits=10, shuffle=True, random_state=_seed)

In [12]:
_start = time.time()
_results = cross_val_score(_estimator, _X, _Y_1hot, cv=_kfold)
_end = time.time()
print('time: {} minutes.'.format((_end-_start)/60))

time: 1.1232110659281414 minutes.


In [13]:
print('Accuracy: {} ({})'.format(_results.mean()*100, _results.std()*100))

Accuracy: 90.00000009934108 (25.690465108350207)
