In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
def get_all_doxy_donkey_posts(_url,_links):
    _response = requests.get(_url)
    _response.raise_for_status()
    _soup = BeautifulSoup(_response.content, 'lxml')
    for _a in _soup.findAll('a'):
        try:
            _url = _a['href']
            _title = _a['title']
            if _title == "Older Posts":
                _links.append(_url)
                get_all_doxy_donkey_posts(_url,_links)
        except:
            _title = ""
    return

_blogUrl = "http://doxydonkey.blogspot.in"
_links = []
get_all_doxy_donkey_posts(_blogUrl,_links)

In [3]:
_links[:19]

['http://doxydonkey.blogspot.in/search?updated-max=2017-04-09T18:57:00-07:00&max-results=7',
 'http://doxydonkey.blogspot.in/search?updated-max=2017-03-29T19:55:00-07:00&max-results=7&start=7&by-date=false',
 'http://doxydonkey.blogspot.in/search?updated-max=2017-03-19T20:14:00-07:00&max-results=7&start=14&by-date=false',
 'http://doxydonkey.blogspot.in/search?updated-max=2017-03-01T19:14:00-08:00&max-results=7&start=21&by-date=false',
 'http://doxydonkey.blogspot.in/search?updated-max=2017-02-20T18:07:00-08:00&max-results=7&start=28&by-date=false',
 'http://doxydonkey.blogspot.in/search?updated-max=2017-02-09T18:22:00-08:00&max-results=7&start=35&by-date=false',
 'http://doxydonkey.blogspot.in/search?updated-max=2017-01-31T17:57:00-08:00&max-results=7&start=42&by-date=false',
 'http://doxydonkey.blogspot.in/search?updated-max=2017-01-19T17:44:00-08:00&max-results=7&start=49&by-date=false',
 'http://doxydonkey.blogspot.in/search?updated-max=2017-01-10T18:06:00-08:00&max-results=7&start

In [7]:
def get_doxy_donkey_post_text(_url):
    _response = requests.get(_url)
    _response.raise_for_status()
    _soup = BeautifulSoup(_response.content,'lxml')
    _divs = _soup.findAll("div", {"class":'post-body'})
    
    _posts =[]
    for _div in _divs:
        _posts += map(lambda _p:_p.text.encode('ascii', errors='replace').decode().replace("?"," "), _div.findAll("li"))
    return _posts

In [8]:
_doxy_donkey_post_text = []
for _link in _links:
    _doxy_donkey_post_text += get_doxy_donkey_post_text(_link)

In [77]:
len(_doxy_donkey_post_text)

2720

In [9]:
_doxy_donkey_post_text[:2]

['Lyft Gets $500 Million in New Funding as Its Rival Uber Wobbles: For years, Lyft has trailed its larger rival Uber in the battle to conquer the ride-hailing market. More recently, Lyft has gotten a boost. The smaller ride-hailing company has secured up to $500 million in a new round of funding that values Lyft at $6.9 billion before the addition of new capital, according to two people briefed on the discussions, who asked to remain anonymous because the details were confidential. The privately held company may raise an additional $100 million, these people said. The financing gave Lyft a $2.4 billion increase in value since the company last raised money in 2016. It was not immediately clear which investors were participating in the new financing. Lyft s previous investors included the venture capital firm Andreessen Horowitz and Chinese e-commerce company Alibaba. Lyft is being bolstered by the woes at Uber, which has been dealing with scandals involving the company s workplace cultu

In [90]:
# http://www.scipy-lectures.org/advanced/scipy_sparse/csr_matrix.html
# Compressed Sparse Row Format

from scipy import sparse

row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
mtx = sparse.csr_matrix((data, (row, col)), shape=(3, 3))
mtx

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [91]:
print('mtx type:\n{}'.format(type(mtx)))
print('mtx:\n{}'.format(mtx))  
print('mtx data:\n{}'.format(mtx.data))
print('mtx indices:\n{}'.format(mtx.indices))
print('mtx indptr:\n{}'.format(mtx.indptr))
print('mtx[0]:\n{}'.format(mtx[0]))
print('mtx[1]:\n{}'.format(mtx[1]))
print('mtx[2]:\n{}'.format(mtx[2]))
print('mtx.todense():\n{}'.format(mtx.todense()))

mtx type:
<class 'scipy.sparse.csr.csr_matrix'>
mtx:
  (0, 0)	1
  (0, 2)	2
  (1, 2)	3
  (2, 0)	4
  (2, 1)	5
  (2, 2)	6
mtx data:
[1 2 3 4 5 6]
mtx indices:
[0 2 2 0 1 2]
mtx indptr:
[0 2 3 6]
mtx[0]:
  (0, 0)	1
  (0, 2)	2
mtx[1]:
  (0, 2)	3
mtx[2]:
  (0, 0)	4
  (0, 1)	5
  (0, 2)	6
mtx.todense():
[[1 0 2]
 [0 0 3]
 [4 5 6]]


In [11]:
# Feature extraction is very different from Feature selection: 
# The former consists in transforming arbitrary data, such as text or images, into numerical features usable 
# for machine learning. The latter is a machine learning technique applied on these features.

# Read 4.2.3 Text feature extraction of:
# http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
_vectorizer = TfidfVectorizer(max_df=0.5, min_df=2, stop_words='english')

In [13]:
type(_vectorizer)

sklearn.feature_extraction.text.TfidfVectorizer

In [16]:
X = _vectorizer.fit_transform(_doxy_donkey_post_text)
X

<2720x13036 sparse matrix of type '<class 'numpy.float64'>'
	with 272341 stored elements in Compressed Sparse Row format>

In [58]:
X_feature_names = _vectorizer.get_feature_names()
len(X_feature_names)

13036

In [70]:
X_feature_names[600]

'abc'

In [76]:
X.toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [92]:
X[2719]

<1x13036 sparse matrix of type '<class 'numpy.float64'>'
	with 40 stored elements in Compressed Sparse Row format>

In [75]:
print('{}'.format(X[0]))

  (0, 7097)	0.569595161783
  (0, 5262)	0.0700602601136
  (0, 396)	0.118132551753
  (0, 7467)	0.0963956010011
  (0, 7825)	0.115382094654
  (0, 5143)	0.113124391152
  (0, 9924)	0.128075641977
  (0, 12155)	0.22252806633
  (0, 12967)	0.0407374611878
  (0, 11948)	0.115162237042
  (0, 6722)	0.0680265301427
  (0, 1588)	0.0799061050617
  (0, 2873)	0.120727332597
  (0, 9888)	0.124227255471
  (0, 5516)	0.132677365117
  (0, 7223)	0.0390658829355
  (0, 9418)	0.0570476676203
  (0, 5358)	0.100486651575
  (0, 1854)	0.0685825333755
  (0, 10701)	0.0703723361386
  (0, 10267)	0.0947831490321
  (0, 10001)	0.0562239519141
  (0, 12439)	0.0871826963202
  (0, 1720)	0.064482905215
  (0, 740)	0.0723795887207
  :	:
  (0, 2442)	0.052573486422
  (0, 2698)	0.0508416155522
  (0, 938)	0.0560905678152
  (0, 1827)	0.115162237042
  (0, 12864)	0.117711818166
  (0, 3354)	0.103697902476
  (0, 10157)	0.115162237042
  (0, 6369)	0.101489354849
  (0, 12895)	0.102556792213
  (0, 3237)	0.0885428765226
  (0, 868)	0.08366702814
  

In [26]:
from sklearn.cluster import KMeans

In [27]:
km = KMeans(n_clusters = 3, init = 'k-means++', max_iter = 100, n_init = 1, verbose = True)

In [28]:
km.fit(X)

Initialization complete
Iteration  0, inertia 5149.220
Iteration  1, inertia 2601.262
Iteration  2, inertia 2593.876
Iteration  3, inertia 2591.752
Iteration  4, inertia 2590.196
Iteration  5, inertia 2589.578
Iteration  6, inertia 2589.430
Iteration  7, inertia 2589.356
Iteration  8, inertia 2589.311
Iteration  9, inertia 2589.271
Iteration 10, inertia 2589.239
Iteration 11, inertia 2589.211
Iteration 12, inertia 2589.184
Iteration 13, inertia 2589.140
Iteration 14, inertia 2589.075
Iteration 15, inertia 2589.017
Iteration 16, inertia 2588.966
Iteration 17, inertia 2588.942
Iteration 18, inertia 2588.932
Iteration 19, inertia 2588.923
Iteration 20, inertia 2588.896
Iteration 21, inertia 2588.877
Iteration 22, inertia 2588.876
Converged at iteration 22: center shift 0.000000e+00 within tolerance 7.409231e-09


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
    n_clusters=3, n_init=1, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=True)

In [98]:
km.labels_

array([2, 2, 2, ..., 2, 1, 2], dtype=int32)

In [99]:
len(km.labels_)

2720

In [96]:
km.cluster_centers_

array([[  4.15370803e-04,   4.75180056e-03,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.30648178e-04,   8.40625025e-03,   5.54647198e-05, ...,
          0.00000000e+00,   1.68266659e-04,   1.10237007e-04],
       [  7.93802821e-04,   8.18578801e-03,   1.46484929e-04, ...,
          2.37243213e-04,   0.00000000e+00,   1.00115569e-03]])

In [101]:
len(km.cluster_centers_)

3

In [29]:
import numpy as np

In [30]:
np.unique(km.labels_, return_counts = True)

(array([0, 1, 2], dtype=int32), array([ 187, 1576,  957]))

In [115]:
_text = {}
for _idx, _cluster in enumerate(km.labels_):
    _document = _doxy_donkey_post_text[_idx]
    if _cluster not in _text.keys():
        _text[_cluster] = _document
    else:
        _text[_cluster] += _document

In [116]:
print(len(_text))
print(len(_text[0]))
print(len(_text[1]))
print(len(_text[2]))
print(_text[0][0:1000])

3
309508
2483667
1395004
Australian regulator sues Apple alleging iPhone 'bricking': Australia's consumer watchdog has sued Apple Inc (AAPL.O) alleging it used a software update to disable iPhones which had cracked screens fixed by third parties. The U.S. technology giant "bricked" - or disabled with a software update - hundreds of smartphones and tablet devices, and then refused to unlock them on the grounds that customers had had the devices serviced by non-Apple repairers, the Australian Competition and Consumer Commission said in a court filing. "Consumer guarantee rights under the Australian Consumer Law exist independently of any manufacturer's warranty and are not extinguished simply because a consumer has goods repaired by a third party," ACCC Chairman Rod Sims said in a statement. The regulator said that between September 2014 and February 2016, Apple customers who downloaded software updates then connected their devices to their computers received a message saying the device 

In [117]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist
from collections import defaultdict
from string import punctuation
from heapq import nlargest
import nltk

In [118]:
_stopwords = set(stopwords.words('english') + list(punctuation)+["million","billion","year","millions","billions","y/y","'s","''","``"])

In [120]:
_keywords = {}
_counts={}
for _cluster in range(3):
    _word_sent = word_tokenize(_text[_cluster].lower())
    _word_sent=[_word for _word in _word_sent if _word not in _stopwords]
    _freq = FreqDist(_word_sent)
    _keywords[_cluster] = nlargest(100, _freq, key=_freq.get)
    _counts[_cluster]=_freq

In [121]:
print(_keywords)

{0: ['apple', 'company', 'said', 'iphone', 'new', 'percent', 'sales', 'pay', 'china', 'watch', 'also', 'market', 'app', 'google', 'mobile', 'samsung', 'according', 'quarter', 'last', 'first', 'would', 'apps', 'one', 'service', 'iphones', 'like', 'smartphone', 'devices', 'store', 'revenue', 'could', 'people', 'years', 'technology', 'phones', 'music', 'may', 'u.s.', 'phone', 'payments', 'time', 'use', 'make', 'sold', 'stores', 'world', 'customers', 'companies', 'business', 'data', 'product', 'android', 'smartphones', 'users', 'since', 'services', 'cook', 'device', 'two', 'much', 'india', 'software', 'products', 'analyst', 'buy', 'research', 'inc.', 'many', 'well', 'consumers', 'tv', 'months', 'shares', 'maker', 'still', 'system', 'growth', 'reported', 'even', 'government', 'ipad', 'credit', 'used', 'including', 'profit', '6', 'chinese', 'industry', 'next', 'analysts', 'firm', 'chief', 'less', 'already', 'electronics', 'price', 'payment', 'big', 'executive', 'streaming'], 1: ['company', '

In [122]:
print(_counts)

{0: FreqDist({'apple': 1253, 'company': 317, 'said': 310, 'iphone': 259, 'new': 215, 'percent': 213, 'sales': 201, 'pay': 197, 'china': 176, 'watch': 166, ...}), 1: FreqDist({'company': 1991, 'said': 1804, 'google': 1488, 'facebook': 1451, 'new': 1396, 'amazon': 1220, 'users': 1094, 'like': 1065, 'also': 993, 'people': 907, ...}), 2: FreqDist({'company': 2150, 'percent': 1851, 'said': 1363, 'revenue': 1115, 'investors': 756, 'shares': 743, 'quarter': 710, 'last': 684, 'new': 665, 'china': 665, ...})}


In [127]:
_unique_keys={}
for _cluster in range(3):   
    print(_cluster)
    _other_clusters=list(set(range(3))-set([_cluster]))
    print(_other_clusters)
    _keys_other_clusters=set(_keywords[_other_clusters[0]]).union(set(_keywords[_other_clusters[1]]))
    _unique=set(_keywords[_cluster])-_keys_other_clusters
    _unique_keys[_cluster]=nlargest(10, _unique, key=_counts[_cluster].get)

0
[1, 2]
1
[0, 2]
2
[0, 1]


In [128]:
_unique_keys

{0: ['apple',
  'iphone',
  'watch',
  'samsung',
  'iphones',
  'smartphone',
  'store',
  'music',
  'phones',
  'phone'],
 1: ['facebook',
  'twitter',
  'ads',
  'video',
  'search',
  'ad',
  'mr.',
  'get',
  'way',
  'social'],
 2: ['investors',
  'alibaba',
  'share',
  'stock',
  'public',
  'round',
  'valuation',
  'capital',
  'raised',
  'per']}

In [130]:
article = "Facebook Inc. has been giving advertisers an inflated metric for the average time users spent watching a video, a measurement that may have helped boost marketer spending on one of Facebook’s most popular ad products. The company, owner of the world’s largest social network, only counts a video as viewed if it has been seen for more than 3 seconds. The metric it gave advertisers for their average video view time incorporated only the people who had watched the video long enough to count as a view in the first place, inflating the metric because it didn’t count anyone who didn’t watch, or watched for a shorter time. Facebook’s stock fell more than 1.5 percent in extended trading after the miscalculation was earlier reported in the Wall Street Journal. Facebook had disclosed the mistake in a posting on its advertiser help center web page several weeks ago. Big advertising buyers and marketers are upset about the inflated metric, and asked the company for more details, according to the report in the Journal, citing unidentified people familiar with the situation. The Menlo Park, California-based company has kept revenue surging in part because of enthusiasm for its video ads, which advertisers compare in performance to those on Twitter, YouTube and around the web."

In [131]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X,km.labels_)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [133]:
_test = _vectorizer.transform([article.encode('ascii',errors='ignore')])

In [134]:
_test

<1x13036 sparse matrix of type '<class 'numpy.float64'>'
	with 85 stored elements in Compressed Sparse Row format>

In [135]:
classifier.predict(_test)

array([1], dtype=int32)